### ISSUE TITLE
Remove dependency on RGL

### ISSUE THREAD

**Issue by kharus** [smucclaw/baby-l4#12]
According to @inariksit [details](https://github.com/smucclaw/baby-l4/pull/10#issuecomment-785082981)
we only need a small portion of RGL so it's possible to store it as a resource in project repo instead of requiring full dependency on RGL.
This will simplify build process which will benefit both new joiners and also we can set up CI.

**Comment by mengwong** [comment]
Have we considered the possibility of making gf-rgl a git submodule? Would this approach make the build easier by allowing the GF_LIB_PATH to just point to a relative dir under the source tree?

**Comment by inariksit** [comment]
I was unclear in my comment in the last issue, I apologise for misleading. I was confusing two things even for myself:
1. **The core grammar**, which has just the syntactic functions, and new lexicon is just constructed as strings. This one we can commit to the repo as a PGF, and that way not need to depend on RGL or Wordnet.
2. Dynamically created lexicon for each L4 file. This lexicon is generated from the `lexicon` tag in the L4 file, and compiled on the fly.

Alternative to 2 is that we have one large PGF file that includes all of WordNet. But longer-term, I don't think that's a feasible solution, because not all words are in WordNet and we want to allow the user to define their own lexicon. So some dynamic lexicon management is needed.

There are ongoing developments in the GF core team that will allow dynamic lexicon, and not need to recompile the GF grammars when adding new lexicon. I don't know how long it will take that this is usable, but I see new pushes frequently, and this is a priority to more people than just us. So I am very confident that this will be a thing soon.

Short-term, I see a couple of ways to make this work:
* We do dynamic lexicon and require everyone in the development team to have GF, GF-RGL and GF-Wordnet in their paths.
* We don't do dynamic lexicon, either
  * We commit in a huge GF grammar with all of WordNet  lexicon, or
  * We commit in the current syntactic-functions-only grammar, and create new lexicon as string literals (will only work for English).

**Comment by anka-213** [comment]
Should I close this for now?
