### ISSUE TITLE
Clear diagnostics when they are no longer relevant.

### ISSUE THREAD

**Issue by anka-213** [smucclaw/baby-l4#19]
If you give no diagnostics, it will interpret it as no change instead of as no errors.

See here
https://hackage.haskell.org/package/lsp-1.1.1.0/docs/Language-LSP-Diagnostics.html

**Comment by ffrixslee** [comment]
Hi @anka-213 ! I'm not an expert and have never worked on lsp before but someone else was facing a similar issue: [](https://github.com/alanz/lsp/issues/139)
Their solution was "...`Map.singleton (Just defaultDiagnosticSource) (Data.SortedList.toSortedList [])` instead of an empty map"
What would you have me do ?

**Comment by anka-213** [comment]
Thanks for doing the research! This info definitely makes it easier!
